### ISSUE TITLE
JMusic-Bot LICENSE

### ISSUE THREAD

**Issue by smile2468** [haribosinging/SingingHaribo#2]
배포시 의무사항:
수취인에게 라이선스 사본 제공
수정된 파일에 대해 수정사항을 표시한 안내문구 첨부
저작권, 특허, 상표, attribution에 대한 고지사항을 소스코드 또는 "NOTICE" 파일 등에 포함
최초개발자 등을 위해 보증을 면제하고, 책임을 제한

https://www.olis.or.kr/license/Detailselect.do?lId=1002

**Comment by JellyBrick** [comment]
JMusicBot 기반이 아닙니다.

봇을 만들때 참고한 것은 맞으나,

하리보는 JDA & JDA-reactor & jda-utilities & lavaplayer를 사용하여, Kotlin으로 처음부터 작성되었습니다.
